version: '2'


services:
  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - drupal-data:/var/lib/postgresql/data

  drupal:
    build: .
    image: custom-drupal
    ports:
      - 80:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
    
volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
